### ISSUE TITLE
Sync Cancelled

### ISSUE THREAD

**Issue by llvasconcellos** [projectbuendia/client#191]
I'm seeing this exception quite often in the logs.

``` java
12-21 20:10:02.314  23620-24632/org.projectbuendia.client.dev E/buendia/SyncAdapter﹕ Sync canceled
    java.util.concurrent.CancellationException: Sync cancelled before SYNC_CONCEPTS
            at org.projectbuendia.client.sync.SyncAdapter.checkCancellation(SyncAdapter.java:247)
            at org.projectbuendia.client.sync.SyncAdapter.onPerformSync(SyncAdapter.java:191)
            at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
```

**Comment by capnfabs** [comment]
Hey @llvasconcellos, when reporting bugs, please take an Android bug report so that there's more information. `Settings --> Developer Tools --> Take bug report`, or turn on the `Power Button Bug Reports` option.

**Comment by capnfabs** [comment]
As for the actual report, we cancel syncs in two places in the code:
1. When the `PatientChartActivity` is open, we sync observations every minute. Because we want to make sure that this sync happens quickly, we cancel any existing sync first (which might be a slower full sync). See https://github.com/projectbuendia/client/blob/dev/app/src/main/java/org/projectbuendia/client/sync/SyncAccountService.java#L96
2. When the user explicitly clicks the 'Cancel Sync' button, which is shown on the first sync only on the Location List screen (I _think_).

So this isn't a bug unless it's actually preventing sync from being completed. I'm going to downgrade the log level so it doesn't create confusion in the future.

**Comment by llvasconcellos** [comment]
@capnfabs OK for the bug report. I'll do it next time.
