### ISSUE TITLE
2nd row not showing for custom tiles

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/client#202]
Our tiles allow two rows of text.

The second row is coming out as just a hyphen even if a value has been entered.

For example, the tile labelled "Caretaker" in profile "nutrition-itfc-102-v8.csv" is defined as follows:

| concept | type | label | format |
| --- | --- | --- | --- |
| 1777000133, 1777000129 | custom | Caretaker | {1,text}<br/>{2,text} |

Despite entering a value for both concepts 1777000133 and 1777000129, in this case for test patient "ABC/246. Albert Bisset", the second row shows up with just a hyphen.

**Comment by capnfabs** [comment]
I've attached the profile @dancunningham is referring to.

Dan, please attach profiles when you encounter bugs in the future :)
[nutrition-itfc-102-v8.csv.zip](https://github.com/projectbuendia/client/files/95366/nutrition-itfc-102-v8.csv.zip)

**Comment by capnfabs** [comment]
Those concepts are "Caretaker name" and "Village", and for that profile, they're in the "Admission and History" form.

**Comment by capnfabs** [comment]
Ok, the problem is that the client doesn't think that concept #1777000129 has a type, and so it treats the related obs as a null value.

This is super weird, because they've both got the same type - they are Free Text values.

Running `SELECT * FROM concepts WHERE uuid LIKE '1777000129%'` on the SQLite DB on the client returns the empty result set, so it looks like the concept isn't being fetched.

**Comment by capnfabs** [comment]
The reason why the concept isn't being fetched is because the concept isn't keyed as the primary concept on any field in the chart.

Here's the relevant `field` on the server:

``` json
{
    "data":
    [
        {
            "field_id": 838,
            "name": "Caretaker",
            "description": "{\"label\": \"Caretaker\", \"concepts\": [1777000133, 1777000129], \"format\": \"{1,text}\n{2,text}\", \"type\": \"custom\"}",
            "field_type": 1,
            "concept_id": 1777000133,
            "table_name": null,
            "attribute_name": null,
            "default_value": null,
            "select_multiple": 0,
            "creator": 3,
            "date_created": "2016-01-19 13:14:15",
            "changed_by": null,
            "date_changed": null,
            "retired": 0,
            "retired_by": null,
            "date_retired": null,
            "retire_reason": null,
            "uuid": "954d9f15-e854-4a16-ac87-6bed755995f3"
        }
    ]
}
```

You can see that the first concept is taken and put into the `concept_id` field, but the second isn't. That `concept_id` field is what the fetch logic in `ConceptResource` uses to work out if a concept should be fetched or not.

The solution is to unpack that JSON `description` field and look for additional concepts there.
