### ISSUE TITLE
Loading and Sync: Not all patients loading when you initiate server.

### ISSUE THREAD

**Issue by saratheneale** [projectbuendia/client#321]
I tried it with 2 servers - demo and NUC2. 
I tried it with devices set at the current time AND devices with backdated times.
This bug (Not all patients are loading) happens in all cases. 

1. Load the NUC2 server and wait for sync
2. Observe that All Patients is equal to 0. 
3. Search by Patient ID for 001 and observe the patient might appear in the result or list. 
4. If the patient doesn't appear, try to add a patient with `id: 001` 
Result: It fails to add because a patient already exists. Now the patient with 001 is in the All patients list.  

with demo.buendia.org - 

1. Load the demo.buendia.org server and wait for sync
2. Go to All Patients (says 144 as of this writing). (But the DB has more. @zestyping was looking at this). 
3. Search by ID for 72. 
Result: No such patient found
Expected: Patient with ID of 72 is in there. 
Sometimes the search by ID will find the patient and add it to the Patient List.

**Comment by zestyping** [comment]
An important qualifier: has this only been known to happen when the tablet's clock is set to something significantly different from the server's time?  Has it ever happened when the clock is correct?

**Comment by saratheneale** [comment]
@zestyping This happens in both cases - 
1) when you have the automatic date and time set 
2) when the device is manually set with a past time.

**Comment by zestyping** [comment]
Investigation has revealed so far that:

  - The SQL query being used to retrieve the patients performs a `join` against the `buendia_patient_sync_map` table (a table I don't remember knowing the purpose of!)
  - The `patient` table contains all 395 patients, but the `buendia_patient_sync_map` table contains only 168 patients.  I have confirmed that these 168 patients are precisely the ones that show up on the tablet.
  - There is no way we intended for only those 168 patients to appear, because if you tap the magnifying glass on the tablet ("Go to patient chart") and type in one of the patient IDs that doesn't have a `date_changed`, the tablet queries for just that one patient record, and the server returns it!  Merely trying to navigate to one of the missing patients causes the patient to appear and the total number of patients on the tablet to increase by 1.

A missing patient can be fixed:

  - These 168 patients are also exactly the ones that have a non-null `date_changed` column in the `patient` table.
  - If I make an edit to one of the missing patients (e.g. add one letter to the name), that causes the patient to have a `date_changed` value, and if I then clear and re-sync the tablet, that patient now becomes part of the set of properly loaded patients.

Thus, the initial set of loaded patients contains _all patients that have been edited at least once_.

**Comment by zestyping** [comment]
Found the answer: https://github.com/projectbuendia/client/issues/187

And the solution: https://github.com/projectbuendia/buendia/pull/60/files

It's a server-side fix.  Thanks, @capnfabs!

**Comment by zestyping** [comment]
I believe this is fixed.  I have tested it locally and it seems to work, so I'm trying to release this as server version 0.11.  Consulting @schuyler to find out why CircleCI builds the release but isn't publishing it to GitHub.

Note: The nature of this problem is that it occurs when the patient is _added_, not when patients are synced.  It is possible for a patient to be added in such a way that the patient is missing from sync.  I made all 400 patients appear by updating their timestamps, but to truly test whether this fix is good, we should add a lot of patients and make sure they all show up.

**Comment by capnfabs** [comment]
lollll this is some _insane_ thread necromancy here 😅 I don't know what y'all are up to with this project (I think I got a twitter notification?) but all the best with it and let me know if you have any questions about anything; I don't think I can actually remember any of the decisions I made from back then but I'm happy to help wherever I can.

**Comment by zestyping** [comment]
Thanks @capnfabs!  At MSF OCG's request, we are reviving Buendia for the Ebola outbreak in DRC!

@saratheneale We think this is fixed on staging.buendia.org — could you spend a few minutes verifying and then close this if it's good?  (I know that truly achieving high confidence would require adding lots of patients, but I think only a best effort is needed because I'm pretty sure we understand the problem.  If it happens again we can reopen this issue.)

**Comment by saratheneale** [comment]
Verified fixed on staging.buendia.org with 0.13.1
