### ISSUE TITLE
Patient Record Observations -> O2 saturation % showing #'%'

### ISSUE THREAD

**Issue by saratheneale** [projectbuendia/client#322]
1. Go to a patient with observations
2. In the view only mode, look at the `O2 Saturation` column. 
Result: It says `#'%'`
Expected: It should have a number in it.

**Comment by zestyping** [comment]
This is happening because ExtendedMessageFormat is refusing to accept `{1,number,#'%'}` as a valid pattern, which is due to a bug in ExtendedMessageFormat, unfortunately.  The parsing method `parseFormatDescription` handles quote marks improperly, skipping an extra character after the closing `'` and thus missing the closing `}`.  This causes it to throw an exception, and when that happens, we show the literal pattern instead of formatting the value.
