### ISSUE TITLE
Drop-down list of 10 most common medications

### ISSUE THREAD

**Issue by daisuke-plangrid** [projectbuendia/client#341]

**Comment by zestyping** [comment]
#### Part A. User interface

The treatment dialog (see OrderDialog) has a text entry field (mMedication) for the name of the medication.  To facilitate data entry, we want to provide a drop-down list where the user can select a commonly prescribed medication from a list of 10 medications, where the list of common medications is configured in the profile.  The text field should still be editable so that user can enter anything else.

If implementing Part A by itself, you could just use a static array of medications as a stand-in.  When Part B is ready, query the chart_items table to get the list of common medications.

#### Part B. Data flow

As background, please read:

- The wiki page "Profiles" for details on the layout of the CSV file.

- The wiki page "Concepts and their UI strings"

- The wiki page "Client data model"

- The schema definition for the client database in org.projectbuendia.client.sync.Database.

The list of common medications needs to be stored on both the client and the server.

The server can store the list of common medications in an OpenMRS form object.  Both what we call "charts" and "forms" in the profile are currently compiled into OpenMRS form objects and are visible in Administration > Forms > Manage Forms.  The easiest way to define this is to choose a special identifier for this purpose and add the list of common medications as a new "chart" block in the profile with this special identifier as its name.  This special chart will have a CSV row for each medication, with the medication's name and concept ID.  The list doesn't have to have exactly 10 medications; it could be any size.  This chart block will become an OpenMRS form when the profile is loaded.

The client downloads charts and forms from the server during sync.  They get stored in local SQL tables; the charts go in the chart_items table.  To get the list, the client should query the chart_items table for items in the chart with the special identifier.
