### ISSUE TITLE
Can't add : char to Buendia server address

### ISSUE THREAD

**Issue by llvasconcellos** [projectbuendia/client#58]
In settings I can't add : and / to the server address and this is required to change it. Log cat says this:

10-08 11:13:37.372    8765-8765/org.projectbuendia.client.dev E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length

**Comment by llvasconcellos** [comment]
I just realized this isn't a bug but then we need to say something to the user.

**Comment by llvasconcellos** [comment]
The same happens when adding a new patient. The ID field does not allow some characters but it doesn't give feedback to the user.

**Comment by capnfabs** [comment]
Hey @llvasconcellos, are you referring to the 'General --> Buendia server' setting or to the 'Advanced --> OpenMRS base URL' setting? If you're referring to the 'General --> Buendia server' setting, I can't even type those characters into the textbox.

**Comment by zestyping** [comment]
Yes, that's intentional.  The server setting is just for a hostname.  If
you want to specify a custom port or path, you edit the URL in the advanced
settings (and if you do so the server setting disappears because it no
longer applies).  It's separated this way because we don't want most users
to have to deal with API URLs.
